version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      angular:
        patterns: ["@angular/*"]
      electron:
        patterns: ["electron", "electron-builder", "@electron/*"]
  - package-ecosystem: pip
    directory: /apps/indexer
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
